parameters:
  devstack.oauth.yammer:
    clientId: LuS8cugzQhekaS0JpQKXA
    clientSecret: tppom1xvaGERPZoHkCaDYytNENoshyXrHe8EARNY
    scope: ['email']

services:
    devstack.ballot_box:
        class: Accord\DevStackBundle\Vote\BallotBox
        arguments: ['@doctrine.orm.entity_manager']
        
    devstack.finder_factory:
        class: Accord\DevStackBundle\Finder\Factory
        arguments: ['@doctrine.orm.entity_manager', '@router', '@devstack.pager_factory', '@validator']
        
    devstack.pager_factory:
        class: Accord\DevStackBundle\Pager\Factory
        arguments: ['@router']
        
    devstack.oath.yammer:
        class: Accord\DevStackBundle\OAuth\Yammer
        arguments: ['@router', '@service_container']