services:
    devstack.ballot_box:
        class: Accord\DevStackBundle\Vote\BallotBox
        arguments: ['@doctrine.orm.entity_manager']
        
    devstack.finder_factory:
        class: Accord\DevStackBundle\Finder\Factory
        arguments: ['@doctrine.orm.entity_manager', '@router', '@devstack.pager_factory', '@validator']
        
    devstack.pager_factory:
        class: Accord\DevStackBundle\Pager\Factory
        arguments: ['@router']